### ISSUE TITLE
Missing provider when using forFeature

### ISSUE THREAD

**Issue by ekrapfl** [Michsior14/ngrx-addons#180]
Reproduction:
https://stackblitz.com/edit/angular-uxh6gr?file=src/main.ts

I am getting the following error when I try to use `PersistStateModule.forFeature()`:
`NullInjectorError: No provider for PersistState!`

If you uncomment the `PersistStateModule.forRoot()` call just above `PersistStateModule.forFeature()` in `main.ts`, it will work fine.

I did some digging, and I assume it is just a missing provider [here](https://github.com/Michsior14/ngrx-addons/blob/bb5a2f1b53e557bb20e494cf56ff244a2da8f52b/libs/persist-state/src/lib/persist-state.module.ts#L43).
![image](https://github.com/Michsior14/ngrx-addons/assets/5939413/adee2312-c5b8-4bf0-9db7-10563c31daa4)

I would imagine that should look the same as [this one](https://github.com/Michsior14/ngrx-addons/blob/bb5a2f1b53e557bb20e494cf56ff244a2da8f52b/libs/persist-state/src/lib/persist-state.module.ts#L27), right?
![image](https://github.com/Michsior14/ngrx-addons/assets/5939413/001f066b-f49e-488c-9f84-13c78306e750)

I'm not 100% certain if this is a bug, or if I am just confused by the usage and I should always be calling `PersistStateModule.forRoot()`, even if I otherwise only use `PersistStateModule.forFeature()`.

Let me know if I am just using it wrong 😄 

Thanks!

**Comment by Michsior14** [comment]
Yes, `forRoot` should be always called in the `AppModule`, similar to `ngrx` and it's `forFeature` implemention.

I need to admit that docs are wrong in this regard. It should mention such requirement. I could also improve `forRoot` syntax to allow skipping `config` parameter altogether. What do you think?

If you are up to updating docs feel free to raising PR, if not I will try to invest some time in the next days and revisit them.

**Comment by ekrapfl** [comment]
If it is expected to have to call `forRoot`, I am totally fine with the way it currently works.  A small update to the docs would be more than enough.  IMO. I can throw a PR up shortly.

Thanks for the response!

**Comment by ekrapfl** [comment]
PR is up, feel free to take a look.
