### ISSUE TITLE
Is it possible to delay PersistState from rehydrating until after App_Initializer has finished?

### ISSUE THREAD

**Issue by ekrapfl** [Michsior14/ngrx-addons#182]
This is a somewhat complicated scenario.  I have an app that does some things in an Angular `APP_INITIALIZER` function.  Those things are asynchronous.  Without getting into too much detail, I cannot have PersistState rehydrate the data from the database until AFTER the `APP_INITIALIZER` has completed.

[Reproduction](https://stackblitz.com/edit/angular-ivy-lttnkm?file=src/app/app.module.ts)
If you look at the console logs, you will see that the store is being rehydrated before the `APP_INITIALIZER` has run.

I ran into a similar problem with NgRx effects, but I was able to work around it with something like the solutions mentioned [here](https://github.com/ngrx/platform/issues/3659#issuecomment-1317461967).

Basically, using the `APP_BOOTSTRAP_LISTENER` token ensures that `APP_INITIALIZER` has finished.  So I tap into that and manually add our effect to the `EffectSources` at that time.  As opposed to using `EffectsModule.forFeature(effect)` or `EffectsModule.forRoot(effects)`, which has the same problem of running before the `APP_INITIALIZER` has completed.  Here is a more robust example of what that code looks like:
```ts
export const effectBootstrapperProvider = (e: Provider): Provider[] => {
  return [
    e,
    {
      provide: APP_BOOTSTRAP_LISTENER,
      multi: true,
      useFactory: (ef: Provider, sources: EffectSources) => () => sources.addEffects(ef),
      deps: [[new Inject(e)], EffectSources],
    },
  ];
};
```

```ts
@NgModule({
  declarations: [AppComponent],
  imports: [StoreModule.forRoot(reducers), EffectsModule.forRoot()],
  providers: [
    { provide: APP_INITIALIZER, useFactory: appInitializerFactory, multi: true, deps: [AppInitializerService] },
    effectBootstrapperProvider(effects.flatMap(effectBootstrapperProvider)),
  ],
  bootstrap: [AppComponent],
})
export class AppModule {}
```

The problem I am having with PersistState is that I am not positive how to work around this like I could with effects.  Ideally, PersistState would not try to rehydrate until after `APP_INITIALIZER` has finished.  Perhaps that bootstrapping code would happen internally.

Otherwise, I could potentially work around it in the same way as with effects, but only if I have some way to add a `PersistStateFeature` later.  Right now, the types are not exposed such that I could inject `PersistState` myself.

I am open to options here in how to handle this.  Just wondering if there is some other way around, or if I could get some sort of a code change to make it so that rehydration waits for `APP_INITIALIZER` to finish.

Thanks!

**Comment by Michsior14** [comment]
Interesting problem indeed! Since the initialization of all modules is closely related to `ngrx` implementation it shares the same issues as you already noticed. I could think of two workarounds for now:
1. You can signal that initialization before returning anything in `getItem` in your storage implementation, i.e. like [here](https://stackblitz.com/edit/angular-ivy-uwzdcp?file=src/app/app.module.ts).
2. We can expose `PersistState`/`SyncState` so it's possible to do the same as in `ngrx` workarounds.

I could also implement the config option for awaiting of `APP_INITIALIZER` finish state (probably something exactly like in the 1., but on lib level) and set it `off` by default so there is no breaking change.

**Comment by ekrapfl** [comment]
Baked into the lib would be amazing, tbh.  Otherwise, exposing `PersistState`/`SyncState` so I can work around it myself would also be perfectly acceptable.

**Comment by Michsior14** [comment]
Initialization strategies and `PersisState`/`SyncState` exposed in [v3.1.0](https://github.com/Michsior14/ngrx-addons/releases/tag/persist-state-3.1.0).

**Comment by ekrapfl** [comment]
Thank you so much!

**Comment by ekrapfl** [comment]
@Michsior14 
I gave it a shot in an updated [StackBlitz example](https://stackblitz.com/edit/angular-ivy-iszepc?file=src/app/app.module.ts), and it still appears to be firing rehydration before app initialization is completed.  Am I doing it wrong, or is something not quite working right?  I can also open a new issue for this if you would prefer.

**Comment by Michsior14** [comment]
I am not sure if the test it actually correctly checking rehydrate action, it's just confirms that getItem is called (not necessarily resolving). Have a look on the newly crated app `after-init` and you will see that rehydration is indeed fired after the app is initialized.

**Comment by Michsior14** [comment]
But if waiting for storage resolving is also thing you require I can quickly improve this.

**Comment by Michsior14** [comment]
Improved in v3.2.0, I've also checked your [example](https://stackblitz.com/edit/angular-ivy-yvfc38?file=package.json)

**Comment by ekrapfl** [comment]
Yes, that is exactly correct!  I need it to delay accessing the storage at all until after initialization has occurred, which is exactly what your last fix does.  Thanks for fixing again without me even having to ask 😄
