### ISSUE TITLE
Using forFeature multiple times only works for the last one

### ISSUE THREAD

**Issue by ekrapfl** [Michsior14/ngrx-addons#191]
I have a repro [here](https://stackblitz.com/edit/angular-33ldbt?file=src/main.ts) that shows the issue.

I am attempting to use `PersistStateModule.forFeature()` for multiple features.  It works fine for any feature individually, and it works fine if I use `PersistStateModule.forRoot()`.

I expected that I should be able to use `forFeature()` for as many features as I have, right?

**Comment by Michsior14** [comment]
Fixed in 3.2.3, I've also [updated your example](https://stackblitz.com/edit/angular-29ndcv?file=src/main.ts) to confirm.

**Comment by ekrapfl** [comment]
That is working perfectly now, thank you!
